### PR TITLE
Polymorph guide for `GSAP`

### PR DESCRIPTION
**Pull request by xavierfoucrier**
- new guide for `polymorph-js` used with `gsap`
- update of `vuepress`
- drop unused dependencies

### CODE REVIEW

**Comment by xavierfoucrier** [comment]
Hello @notoriousb1t :wave:

Same as I did years ago, I just added a small guide to get started with `polymorph-js` and `gsap`.
> The last "Bump version" commit contains all the compiled `dist` files.

Thanks for the merge!
Enjoy :tada: :sunglasses:

**Comment by xavierfoucrier** [comment]
Bump @notoriousb1t 👋

**Comment by xavierfoucrier** [comment]
Bump @notoriousb1t 👋

**Review by notoriousb1t — APPROVED** [review]

**Comment by notoriousb1t** [comment]
Apologies, I haven't been active in some time. Everything looks good though!

**Comment by xavierfoucrier** [comment]
Hey @notoriousb1t!
Big thanks for that 🚀 ❤️ 

> You will probably need to review your Travis CI in order to push to production, haven't take a look, but it looks not pushed yet to Github Pages. Anyway, big thanks for the merge @notoriousb1t 👍 Don't hesitate to ping me again if needed!

**Comment by xavierfoucrier** [comment]
Hello @notoriousb1t,

Polymorph docs for GSAP is still not pushed to Github Pages.
Thanks for the update! 🤟 ❤️ 

> See https://notoriousb1t.github.io/polymorph-docs/guide/getting-started-gsap.html.

**Comment by xavierfoucrier** [comment]
Hello @notoriousb1t,

Polymorph docs for GSAP is still not pushed to Github Pages.
Thanks for the update! 🤟 ❤️ 

> See https://notoriousb1t.github.io/polymorph-docs/guide/getting-started-gsap.html.

**Comment by notoriousb1t** [comment]
@xavierfoucrier, I have been on a bit of a hiatus on open source for the last few years, but am starting to try to cleanup things. I have upgraded the docs to vuepress 2 rc* and vue3 and switched the deployment from travis to github actions.

Long story short, the page is live now: https://notoriousb1t.github.io/polymorph-docs/guide/getting-started-gsap.html

Thanks for your patience, and also the guide!

**Comment by xavierfoucrier** [comment]
Hello @notoriousb1t 👋 

Great to have some news from you.
Don't worry, I am a very patient man 😉 

Thanks a lot for making the gsap guide live 🚀
See you later for the next update!

**Pull request merged**
